[book]
    title       = "书的标题"
    description = "书的描述"         # 此处 description 会作为元信息添加到页面的 HTML <head> 中
    authors     = ["作者1", "作者2"]
    language    = "zh-CN"
    src         = "src"

[build]
    build-dir = "book"
    epub-dir  = "epub"

[output.linkcheck]
    optional = true

[output.pdf]
    optional = true

[output.html]
    no-section-label = true # 去掉书籍章节的数字前缀

[output.html.fold]
    enable = true # 开启章节折叠
    level  = 1    # 把默认的折叠层级设为 1
