name: ✔️ Task
description: 公示任务
title: "[Task] <title>"
labels: [Task]
body:
  - type: textarea
    attributes:
      label: Task
      description: 这里填写任务以及产出
      placeholder: |
        - 任务（下一步行动）：
        - 截止日期：
        - 预计产出：这里存放信息归档后的位置，可以是 Code，也可以是 Wiki。
        - 每日进展：
    validations:
      required: true
